/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xh_networkclient_HttpRequest */

#ifndef _Included_com_xh_networkclient_HttpRequest
#define _Included_com_xh_networkclient_HttpRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xh_networkclient_HttpRequest
 * Method:    JNIRequest
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xh_networkclient_HttpRequest_JNIRequest
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_xh_networkclient_HttpRequest
 * Method:    JNIDownload
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xh_networkclient_HttpRequest_JNIDownload
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     com_xh_networkclient_HttpRequest
 * Method:    JNIUpload
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xh_networkclient_HttpRequest_JNIUpload
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     com_xh_networkclient_HttpRequest
 * Method:    JNIStop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xh_networkclient_HttpRequest_JNIStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xh_networkclient_HttpRequest
 * Method:    JNISetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xh_networkclient_HttpRequest_JNISetLogLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
