/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xh_networkclient_HttpRequest_Singleton */

#ifndef _Included_com_xh_networkclient_HttpRequest_Singleton
#define _Included_com_xh_networkclient_HttpRequest_Singleton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
